vich_uploader:
    db_driver: orm

    mappings:
        profile_images:
            uri_prefix: /assets/images/uploads/profiles
            upload_destination: '%kernel.project_dir%/public/assets/images/uploads/profiles'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            delete_on_remove: true
            delete_on_update: true